name: CI Python Docker URL Param # Nom de la pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape de construction de l'image Docker
    - name: Build Docker image
      run: docker build -t myapp-ci:${{ github.sha }} .

    # Étape d'exécution des tests DANS l'image construite
    - name: Run tests inside Docker image
      run: docker run --rm myapp-ci:${{ github.sha }} pytest